//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_Warcraft2Simulator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public byte APeasantMaxHitPoints {
            get {
                return ((byte)(this["APeasantMaxHitPoints"]));
            }
            set {
                this["APeasantMaxHitPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte APeasantArmor {
            get {
                return ((byte)(this["APeasantArmor"]));
            }
            set {
                this["APeasantArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte APeasantMovementSpeed {
            get {
                return ((byte)(this["APeasantMovementSpeed"]));
            }
            set {
                this["APeasantMovementSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("peasant_nowp.png")]
        public string PeasantImageSource {
            get {
                return ((string)(this["PeasantImageSource"]));
            }
            set {
                this["PeasantImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("peon_nowp.png")]
        public string PeonImageSource {
            get {
                return ((string)(this["PeonImageSource"]));
            }
            set {
                this["PeonImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public byte AWarriorMaxHitPoints {
            get {
                return ((byte)(this["AWarriorMaxHitPoints"]));
            }
            set {
                this["AWarriorMaxHitPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public byte AWarriorArmor {
            get {
                return ((byte)(this["AWarriorArmor"]));
            }
            set {
                this["AWarriorArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte AWarriorMovementSpeed {
            get {
                return ((byte)(this["AWarriorMovementSpeed"]));
            }
            set {
                this["AWarriorMovementSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("footman.png")]
        public string FootmanImageSource {
            get {
                return ((string)(this["FootmanImageSource"]));
            }
            set {
                this["FootmanImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("grunt.png")]
        public string GruntImageSource {
            get {
                return ((string)(this["GruntImageSource"]));
            }
            set {
                this["GruntImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wow2_128.png")]
        public string TreeImageSource {
            get {
                return ((string)(this["TreeImageSource"]));
            }
            set {
                this["TreeImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wow2_256.png")]
        public string GrassImageSource {
            get {
                return ((string)(this["GrassImageSource"]));
            }
            set {
                this["GrassImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wow2_301.png")]
        public string WaterImageSource {
            get {
                return ((string)(this["WaterImageSource"]));
            }
            set {
                this["WaterImageSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int DrawUnit {
            get {
                return ((int)(this["DrawUnit"]));
            }
            set {
                this["DrawUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte AWarriorDamage {
            get {
                return ((byte)(this["AWarriorDamage"]));
            }
            set {
                this["AWarriorDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte AWarriorRange {
            get {
                return ((byte)(this["AWarriorRange"]));
            }
            set {
                this["AWarriorRange"] = value;
            }
        }
    }
}
